# Generated by Django 4.2.10 on 2024-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseTeamInstructor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_team_id", models.IntegerField()),
                ("course_team_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Course Team Instructor",
                "verbose_name_plural": "Course Team Instructors",
                "unique_together": {("course_team_id", "username")},
            },
        ),
    ]
