"""
Instructor definitions for Open edX Quince release for testing.
"""

ALLOW_STUDENT_TO_BYPASS_ENTRANCE_EXAM = "ALLOW_STUDENT_TO_BYPASS_ENTRANCE_EX"
ENROLLMENT_REPORT = "ENROLLMENT_REPORT"
GIVE_STUDENT_EXTENSION = "GIVE_STUDENT_EXTENSION"
OVERRIDE_GRADES = "OVERRIDE_GRADES"
VIEW_ENROLLMENTS = "VIEW_ENROLLMENTS"
